parameters:
    kernel.log_dir: %kernel.root_dir%/app/logs/
    kernel.template_dir: %kernel.root_dir%/app/templates/
    kernel.service_factory: MicroCMS\DependencyInjection\ServiceFactory

services:
    logger:
       class: Monolog\Logger
       factory_class: %kernel.service_factory%
       factory_method: buildLogger
       arguments: [@service_container]
